[build]
  publish = "."
  command = "echo 'No build command needed'"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# SPA routing
[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/bloxfruit"
  to = "/bloxfruit.html"
  status = 200

[[redirects]]
  from = "/success"
  to = "/order-success.html"
  status = 200

# Netlify Forms
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"